# Generated by Django 2.0 on 2018-01-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genere',
            new_name='genre',
        ),
    ]
