# Generated by Django 2.0 on 2018-01-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180130_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('22222', 'Set book asss returned'),)},
        ),
    ]
