# Generated by Django 2.0 on 2018-01-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180130_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='选择书籍的语言', to='catalog.Language'),
        ),
    ]
